# Generated by Django 4.2.29 on 2026-03-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_embedding_userprofile_age_range_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user'], name='api_rating_user_id_1b0478_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie'], name='api_rating_movie_i_a96108_idx'),
        ),
    ]
