# Generated by Django 4.2.29 on 2026-03-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre'], name='api_movie_genre_5bc1a3_idx'),
        ),
    ]
