# Generated by Django 4.2.29 on 2026-03-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_api_movie_genre_5bc1a3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_animated',
            field=models.BooleanField(default=False),
        ),
    ]
