from django.core.management.base import BaseCommand
from api.models import Movie

MOVIES = [
    dict(tmdb_id=245891, title='John Wick', year=2014, genre='Action', director='Chad Stahelski', cast=['Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen'], avg_rating=7.4, poster_url='https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg', description='An ex-hit-man comes out of retirement to track down the gangsters that took everything from him.'),
    dict(tmdb_id=76341,  title='Mad Max: Fury Road', year=2015, genre='Action', director='George Miller', cast=['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'], avg_rating=8.1, poster_url='https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg', description='In a post-apocalyptic wasteland, Max teams up with Furiosa to flee from a tyrannical warlord.'),
    dict(tmdb_id=155,    title='The Dark Knight', year=2008, genre='Action', director='Christopher Nolan', cast=['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'], avg_rating=9.0, poster_url='https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', description='Batman faces the Joker, a criminal mastermind who plunges Gotham into anarchy.'),
    dict(tmdb_id=361743, title='Top Gun: Maverick', year=2022, genre='Action', director='Joseph Kosinski', cast=['Tom Cruise', 'Miles Teller', 'Jennifer Connelly'], avg_rating=8.3, poster_url='https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg', description='After thirty years, Maverick is still pushing the envelope as a top naval aviator.'),
    dict(tmdb_id=353081, title='Mission: Impossible - Fallout', year=2018, genre='Action', director='Christopher McQuarrie', cast=['Tom Cruise', 'Henry Cavill', 'Ving Rhames'], avg_rating=7.7, poster_url='https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg', description='Ethan Hunt and his IMF team race against time after a mission gone wrong.'),
    dict(tmdb_id=1724,   title='Die Hard', year=1988, genre='Action', director='John McTiernan', cast=['Bruce Willis', 'Alan Rickman', 'Bonnie Bedelia'], avg_rating=8.2, poster_url='https://image.tmdb.org/t/p/w500/yFihWxQcmqcaBR31QM6Y8gT6aYV.jpg', description='An NYPD officer tries to save his wife and several others taken hostage by terrorists.'),
    dict(tmdb_id=11036,  title='The Notebook', year=2004, genre='Romance', director='Nick Cassavetes', cast=['Ryan Gosling', 'Rachel McAdams', 'James Garner'], avg_rating=7.8, poster_url='https://image.tmdb.org/t/p/w500/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg', description='A poor yet passionate young man falls in love with a rich girl, and they fight to be together.'),
    dict(tmdb_id=313369, title='La La Land', year=2016, genre='Romance', director='Damien Chazelle', cast=['Ryan Gosling', 'Emma Stone', 'John Legend'], avg_rating=8.0, poster_url='https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg', description='A jazz musician and an aspiring actress fall in love while pursuing their dreams in Los Angeles.'),
    dict(tmdb_id=597,    title='Titanic', year=1997, genre='Romance', director='James Cameron', cast=['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'], avg_rating=7.9, poster_url='https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', description='A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the Titanic.'),
    dict(tmdb_id=455207, title='Crazy Rich Asians', year=2018, genre='Romance', director='Jon M. Chu', cast=['Constance Wu', 'Henry Golding', 'Michelle Yeoh'], avg_rating=6.9, poster_url='https://image.tmdb.org/t/p/w500/1XxL4LJ5WHdrcYcihEZUCgNCpAW.jpg', description="A New York professor travels to Singapore for her boyfriend's best friend's wedding."),
    dict(tmdb_id=4348,   title='Pride & Prejudice', year=2005, genre='Romance', director='Joe Wright', cast=['Keira Knightley', 'Matthew Macfadyen', 'Rosamund Pike'], avg_rating=7.8, poster_url='https://image.tmdb.org/t/p/w500/o8UhmEbWPHmTUxP0lMuCoqNkbB3.jpg', description='Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy.'),
    dict(tmdb_id=10229,  title='A Walk to Remember', year=2002, genre='Romance', director='Adam Shankman', cast=['Mandy Moore', 'Shane West', 'Peter Coyote'], avg_rating=7.4, poster_url='https://image.tmdb.org/t/p/w500/8lUYMvWdHA0Q0k5F76RQCeCBUkA.jpg', description='The story of two North Carolina teens who come of age through an unlikely romance.'),
    dict(tmdb_id=27205,  title='Inception', year=2010, genre='Sci-Fi', director='Christopher Nolan', cast=['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'], avg_rating=8.8, poster_url='https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', description='A thief who steals corporate secrets through dream-sharing technology is given the inverse task.'),
    dict(tmdb_id=157336, title='Interstellar', year=2014, genre='Sci-Fi', director='Christopher Nolan', cast=['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'], avg_rating=8.6, poster_url='https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', description="A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival."),
    dict(tmdb_id=603,    title='The Matrix', year=1999, genre='Sci-Fi', director='Lana Wachowski', cast=['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'], avg_rating=8.7, poster_url='https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', description='A hacker discovers reality is a simulation and joins a rebellion against its machine overlords.'),
    dict(tmdb_id=329865, title='Arrival', year=2016, genre='Sci-Fi', director='Denis Villeneuve', cast=['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'], avg_rating=7.9, poster_url='https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg', description='A linguist is recruited to communicate with aliens after twelve mysterious spacecraft appear.'),
    dict(tmdb_id=335984, title='Blade Runner 2049', year=2017, genre='Sci-Fi', director='Denis Villeneuve', cast=['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'], avg_rating=8.0, poster_url='https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg', description='A new blade runner unearths a long-buried secret that could plunge society into chaos.'),
    dict(tmdb_id=264660, title='Ex Machina', year=2014, genre='Sci-Fi', director='Alex Garland', cast=['Alicia Vikander', 'Domhnall Gleeson', 'Oscar Isaac'], avg_rating=7.7, poster_url='https://image.tmdb.org/t/p/w500/dmJW8IAKHKxFNiUnoDR7JfsK7Rp.jpg', description='A programmer is selected to evaluate an AI housed in a humanoid robot.'),
    dict(tmdb_id=18785,  title='The Hangover', year=2009, genre='Comedy', director='Todd Phillips', cast=['Bradley Cooper', 'Ed Helms', 'Zach Galifianakis'], avg_rating=7.7, poster_url='https://image.tmdb.org/t/p/w500/uluhlXubGu1VxU63X9VHCLWDAYP.jpg', description='Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night.'),
    dict(tmdb_id=8363,   title='Superbad', year=2007, genre='Comedy', director='Greg Mottola', cast=['Jonah Hill', 'Michael Cera', 'Emma Stone'], avg_rating=7.6, poster_url='https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg', description='Two co-dependent high school seniors are forced to deal with separation anxiety.'),
    dict(tmdb_id=546554, title='Knives Out', year=2019, genre='Comedy', director='Rian Johnson', cast=['Daniel Craig', 'Ana de Armas', 'Chris Evans'], avg_rating=7.9, poster_url='https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg', description='A detective investigates the death of a patriarch of an eccentric, combative family.'),
    dict(tmdb_id=445571, title='Game Night', year=2018, genre='Comedy', director='John Francis Daley', cast=['Jason Bateman', 'Rachel McAdams', 'Kyle Chandler'], avg_rating=7.0, poster_url='https://image.tmdb.org/t/p/w500/85R8LMyn9f2Lev2YPBF8Nughrkv.jpg', description='A group of friends who meet for a regular game night get entangled in a murder mystery.'),
    dict(tmdb_id=12133,  title='Step Brothers', year=2008, genre='Comedy', director='Adam McKay', cast=['Will Ferrell', 'John C. Reilly', 'Mary Steenburgen'], avg_rating=6.9, poster_url='https://image.tmdb.org/t/p/w500/nvggBbEraUTAVR6ffP3AaBUWSHs.jpg', description='Two middle-aged man-children are forced to live together when their single parents marry.'),
    dict(tmdb_id=55721,  title='Bridesmaids', year=2011, genre='Comedy', director='Paul Feig', cast=['Kristen Wiig', 'Maya Rudolph', 'Rose Byrne'], avg_rating=6.8, poster_url='https://image.tmdb.org/t/p/w500/gJtA7hYsBMQ7EM3sPBMUdBfU7a0.jpg', description="Competition between the maid of honor and a bridesmaid over who is the bride's best friend."),
    dict(tmdb_id=419430, title='Get Out', year=2017, genre='Horror', director='Jordan Peele', cast=['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford'], avg_rating=7.7, poster_url='https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg', description="A young Black man visits his white girlfriend's family estate and discovers a disturbing secret."),
    dict(tmdb_id=447332, title='A Quiet Place', year=2018, genre='Horror', director='John Krasinski', cast=['Emily Blunt', 'John Krasinski', 'Millicent Simmonds'], avg_rating=7.5, poster_url='https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg', description='A family struggles to survive in a post-apocalyptic world inhabited by blind monsters with an acute sense of hearing.'),
    dict(tmdb_id=493922, title='Hereditary', year=2018, genre='Horror', director='Ari Aster', cast=['Toni Collette', 'Alex Wolff', 'Milly Shapiro'], avg_rating=7.3, poster_url='https://image.tmdb.org/t/p/w500/hjlZSXM86wJrfCv5VKfR5DI2VeU.jpg', description='A grieving family is haunted by tragic and disturbing occurrences after the death of their grandmother.'),
    dict(tmdb_id=694,    title='The Shining', year=1980, genre='Horror', director='Stanley Kubrick', cast=['Jack Nicholson', 'Shelley Duvall', 'Danny Lloyd'], avg_rating=8.4, poster_url='https://image.tmdb.org/t/p/w500/nRj5511mZdTl4saWEPoj9QroTIu.jpg', description='A family heads to an isolated hotel for the winter where a sinister presence drives the father into madness.'),
    dict(tmdb_id=458156, title='Us', year=2019, genre='Horror', director='Jordan Peele', cast=["Lupita Nyong'o", 'Winston Duke', 'Elisabeth Moss'], avg_rating=6.8, poster_url='https://image.tmdb.org/t/p/w500/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg', description="A family's vacation turns terrifying when they discover sinister doppelgangers of themselves."),
    dict(tmdb_id=530385, title='Midsommar', year=2019, genre='Horror', director='Ari Aster', cast=['Florence Pugh', 'Jack Reynor', 'William Jackson Harper'], avg_rating=7.1, poster_url='https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg', description='A couple travels to Sweden to attend a midsummer festival that devolves into something sinister.'),
    dict(tmdb_id=324857, title='Spider-Man: Into the Spider-Verse', year=2018, genre='Animation', director='Bob Persichetti', cast=['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld'], avg_rating=8.4, poster_url='https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg', description='Teen Miles Morales becomes Spider-Man of his universe and must stop a threat across the multiverse.'),
    dict(tmdb_id=8587,   title='The Lion King', year=1994, genre='Animation', director='Roger Allers', cast=['Matthew Broderick', 'Moira Kelly', 'Nathan Lane'], avg_rating=8.3, poster_url='https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg', description='A lion cub prince flees his kingdom after the murder of his father, only to learn the true meaning of responsibility.'),
    dict(tmdb_id=354912, title='Coco', year=2017, genre='Animation', director='Lee Unkrich', cast=['Anthony Gonzalez', 'Gael García Bernal', 'Benjamin Bratt'], avg_rating=8.2, poster_url='https://image.tmdb.org/t/p/w500/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg', description='Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather.'),
    dict(tmdb_id=315162, title='Puss in Boots: The Last Wish', year=2022, genre='Animation', director='Joel Crawford', cast=['Antonio Banderas', 'Salma Hayek Pinault', 'Harvey Guillén'], avg_rating=8.2, poster_url='https://image.tmdb.org/t/p/w500/kuf6dutpsT0vSVehic3EZIqkOBt.jpg', description='Puss in Boots discovers his passion for adventure has taken a toll: he has burned through eight of his nine lives.'),
    dict(tmdb_id=10681,  title='WALL-E', year=2008, genre='Animation', director='Andrew Stanton', cast=['Ben Burtt', 'Elissa Knight', 'Jeff Garlin'], avg_rating=8.1, poster_url='https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg', description='A robot tasked with cleaning a waste-covered Earth falls in love and goes on a galaxy-spanning adventure.'),
    dict(tmdb_id=1184918, title='The Wild Robot', year=2024, genre='Animation', director='Chris Sanders', cast=["Lupita Nyong'o", 'Pedro Pascal', 'Kit Connor'], avg_rating=8.3, poster_url='https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg', description='A robot shipwrecked on a wild island must adapt to her surroundings and befriend the animals to survive.'),
    dict(tmdb_id=680,    title='Pulp Fiction', year=1994, genre='Thriller', director='Quentin Tarantino', cast=['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'], avg_rating=8.9, poster_url='https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', description='The lives of two mob hitmen, a boxer, and a pair of bandits intertwine in four tales of violence and redemption.'),
    dict(tmdb_id=424,    title="Schindler's List", year=1993, genre='Thriller', director='Steven Spielberg', cast=['Liam Neeson', 'Ralph Fiennes', 'Ben Kingsley'], avg_rating=9.0, poster_url='https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', description='In German-occupied Poland, industrialist Oskar Schindler becomes concerned for his Jewish workforce after witnessing their persecution.'),
    dict(tmdb_id=807,    title='Se7en', year=1995, genre='Thriller', director='David Fincher', cast=['Brad Pitt', 'Morgan Freeman', 'Kevin Spacey'], avg_rating=8.6, poster_url='https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg', description='Two detectives hunt a serial killer who uses the seven deadly sins as motives.'),
    dict(tmdb_id=949,    title='Zodiac', year=2007, genre='Thriller', director='David Fincher', cast=['Jake Gyllenhaal', 'Mark Ruffalo', 'Robert Downey Jr.'], avg_rating=7.5, poster_url='https://image.tmdb.org/t/p/w500/e1GB4SqMbJAqhJlrP3AatUAiYpO.jpg', description='A San Francisco cartoonist becomes an amateur detective obsessed with the Zodiac killer.'),
    dict(tmdb_id=77338,  title='The Intouchables', year=2011, genre='Thriller', director='Olivier Nakache', cast=['Francois Cluzet', 'Omar Sy', 'Anne Le Ny'], avg_rating=8.5, poster_url='https://image.tmdb.org/t/p/w500/1e866QXzi4XKnso6MMlJgE8vMnX.jpg', description='After a paragliding accident, a rich man hires a young man from the projects as his caretaker.'),
    dict(tmdb_id=278,    title='The Shawshank Redemption', year=1994, genre='Drama', director='Frank Darabont', cast=['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'], avg_rating=9.3, poster_url='https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg', description='Two imprisoned men bond over years, finding solace and eventual redemption through acts of decency.'),
    dict(tmdb_id=238,    title='The Godfather', year=1972, genre='Drama', director='Francis Ford Coppola', cast=['Marlon Brando', 'Al Pacino', 'James Caan'], avg_rating=9.2, poster_url='https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLe1rhdVZEuH.jpg', description='The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.'),
    dict(tmdb_id=13,     title='Forrest Gump', year=1994, genre='Drama', director='Robert Zemeckis', cast=['Tom Hanks', 'Robin Wright', 'Gary Sinise'], avg_rating=8.8, poster_url='https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', description='The presidencies of Kennedy and Johnson through the eyes of an Alabama man with an extraordinary life.'),
    dict(tmdb_id=389,    title='12 Angry Men', year=1957, genre='Drama', director='Sidney Lumet', cast=['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'], avg_rating=9.0, poster_url='https://image.tmdb.org/t/p/w500/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg', description='A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.'),
    dict(tmdb_id=497,    title='The Green Mile', year=1999, genre='Drama', director='Frank Darabont', cast=['Tom Hanks', 'Michael Clarke Duncan', 'David Morse'], avg_rating=8.6, poster_url='https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg', description='The lives of guards on Death Row are affected by one of their charges: a massive man with a mysterious gift.'),
    dict(tmdb_id=240,    title='The Godfather Part II', year=1974, genre='Crime', director='Francis Ford Coppola', cast=['Al Pacino', 'Robert De Niro', 'Robert Duvall'], avg_rating=9.0, poster_url='https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', description='The early life of Vito Corleone intercut with the story of his son Michael expanding the family business.'),
    dict(tmdb_id=769,    title='GoodFellas', year=1990, genre='Crime', director='Martin Scorsese', cast=['Ray Liotta', 'Robert De Niro', 'Joe Pesci'], avg_rating=8.7, poster_url='https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg', description='The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen.'),
    dict(tmdb_id=103,    title='Taxi Driver', year=1976, genre='Crime', director='Martin Scorsese', cast=['Robert De Niro', 'Jodie Foster', 'Cybill Shepherd'], avg_rating=8.2, poster_url='https://image.tmdb.org/t/p/w500/ekstpH614fwDX8DUln1a2Opz0N8.jpg', description='A mentally unstable veteran works as a nighttime taxi driver in New York City.'),
    dict(tmdb_id=598,    title='City of God', year=2002, genre='Crime', director='Fernando Meirelles', cast=['Alexandre Rodrigues', 'Leandro Firmino', 'Phellipe Haagensen'], avg_rating=8.6, poster_url='https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2grZ.jpg', description='Two boys growing up in a dangerous neighborhood of Rio de Janeiro take different paths.'),
    dict(tmdb_id=497582, title='Knives Out', year=2019, genre='Crime', director='Rian Johnson', cast=['Daniel Craig', 'Ana de Armas', 'Chris Evans'], avg_rating=7.9, poster_url='https://image.tmdb.org/t/p/w500/pThyQovXQrws2Y4fhB9K5Dq0A6m.jpg', description='A detective investigates the death of a patriarch of an eccentric, combative family.'),
    dict(tmdb_id=120,    title='The Lord of the Rings: The Fellowship of the Ring', year=2001, genre='Adventure', director='Peter Jackson', cast=['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'], avg_rating=8.9, poster_url='https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', description='A meek hobbit and eight companions set out on a journey to destroy the One Ring.'),
    dict(tmdb_id=85,     title='Raiders of the Lost Ark', year=1981, genre='Adventure', director='Steven Spielberg', cast=['Harrison Ford', 'Karen Allen', 'Paul Freeman'], avg_rating=8.4, poster_url='https://image.tmdb.org/t/p/w500/ceG9VzoRAVGwivFU403Wc3AHRys.jpg', description='Archaeologist Indiana Jones races against Nazi Germany to find the legendary Ark of the Covenant.'),
    dict(tmdb_id=329,    title='Jurassic Park', year=1993, genre='Adventure', director='Steven Spielberg', cast=['Sam Neill', 'Laura Dern', 'Jeff Goldblum'], avg_rating=8.2, poster_url='https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg', description='A pragmatic paleontologist visiting a dinosaur theme park clashes with its creator over ethics.'),
    dict(tmdb_id=37724,  title='Skyfall', year=2012, genre='Adventure', director='Sam Mendes', cast=['Daniel Craig', 'Javier Bardem', 'Judi Dench'], avg_rating=7.8, poster_url='https://image.tmdb.org/t/p/w500/xcgNygBNjAqGdN2EhA6AJxCcgep.jpg', description="Bond's loyalty to M is tested as her past comes back to haunt her."),
    dict(tmdb_id=9806,   title='The Incredibles', year=2004, genre='Adventure', director='Brad Bird', cast=['Craig T. Nelson', 'Holly Hunter', 'Samuel L. Jackson'], avg_rating=8.0, poster_url='https://image.tmdb.org/t/p/w500/2LqaLgk4Z226KkgPJuiOQ58ShKD.jpg', description='A family of undercover superheroes tries to live a quiet suburban life but is forced to save the world.'),
]


class Command(BaseCommand):
    help = 'Seed the database with movies'

    def handle(self, *args, **kwargs):
        created = 0
        for m in MOVIES:
            _, was_created = Movie.objects.get_or_create(tmdb_id=m['tmdb_id'], defaults=m)
            if was_created:
                created += 1
        self.stdout.write(self.style.SUCCESS(f'Seeded {created} movies ({len(MOVIES) - created} already existed)'))
