from django.core.management.base import BaseCommand
from api.models import Movie

MOVIES = [
    # Action
    dict(tmdb_id=245891, title='John Wick', year=2014, genre='Action', director='Chad Stahelski', cast=['Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen'], avg_rating=7.4, poster_url='https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg', description='An ex-hit-man comes out of retirement to track down the gangsters that took everything from him.'),
    dict(tmdb_id=76341,  title='Mad Max: Fury Road', year=2015, genre='Action', director='George Miller', cast=['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'], avg_rating=8.1, poster_url='https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg', description='In a post-apocalyptic wasteland, Max teams up with Furiosa to flee from a tyrannical warlord.'),
    dict(tmdb_id=155,    title='The Dark Knight', year=2008, genre='Action', director='Christopher Nolan', cast=['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'], avg_rating=9.0, poster_url='https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', description='Batman faces the Joker, a criminal mastermind who plunges Gotham into anarchy.'),
    dict(tmdb_id=361743, title='Top Gun: Maverick', year=2022, genre='Action', director='Joseph Kosinski', cast=['Tom Cruise', 'Miles Teller', 'Jennifer Connelly'], avg_rating=8.3, poster_url='https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg', description='After thirty years, Maverick is still pushing the envelope as a top naval aviator.'),
    dict(tmdb_id=353081, title='Mission: Impossible - Fallout', year=2018, genre='Action', director='Christopher McQuarrie', cast=['Tom Cruise', 'Henry Cavill', 'Ving Rhames'], avg_rating=7.7, poster_url='https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg', description='Ethan Hunt and his IMF team race against time after a mission gone wrong.'),
    dict(tmdb_id=1724,   title='Die Hard', year=1988, genre='Action', director='John McTiernan', cast=['Bruce Willis', 'Alan Rickman', 'Bonnie Bedelia'], avg_rating=8.2, poster_url='https://image.tmdb.org/t/p/w500/yFihWxQcmqcaBR31QM6Y8gT6aYV.jpg', description='An NYPD officer tries to save his wife and several others taken hostage by terrorists.'),
    # Romance
    dict(tmdb_id=11036,  title='The Notebook', year=2004, genre='Romance', director='Nick Cassavetes', cast=['Ryan Gosling', 'Rachel McAdams', 'James Garner'], avg_rating=7.8, poster_url='https://image.tmdb.org/t/p/w500/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg', description='A poor yet passionate young man falls in love with a rich girl, and they fight to be together.'),
    dict(tmdb_id=313369, title='La La Land', year=2016, genre='Romance', director='Damien Chazelle', cast=['Ryan Gosling', 'Emma Stone', 'John Legend'], avg_rating=8.0, poster_url='https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg', description='A jazz musician and an aspiring actress fall in love while pursuing their dreams in Los Angeles.'),
    dict(tmdb_id=597,    title='Titanic', year=1997, genre='Romance', director='James Cameron', cast=['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'], avg_rating=7.9, poster_url='https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', description='A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the Titanic.'),
    dict(tmdb_id=455207, title='Crazy Rich Asians', year=2018, genre='Romance', director='Jon M. Chu', cast=['Constance Wu', 'Henry Golding', 'Michelle Yeoh'], avg_rating=6.9, poster_url='https://image.tmdb.org/t/p/w500/1XxL4LJ5WHdrcYcihEZUCgNCpAW.jpg', description="A New York professor travels to Singapore for her boyfriend's best friend's wedding."),
    dict(tmdb_id=4348,   title='Pride & Prejudice', year=2005, genre='Romance', director='Joe Wright', cast=['Keira Knightley', 'Matthew Macfadyen', 'Rosamund Pike'], avg_rating=7.8, poster_url='https://image.tmdb.org/t/p/w500/o8UhmEbWPHmTUxP0lMuCoqNkbB3.jpg', description='Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy.'),
    dict(tmdb_id=10229,  title='A Walk to Remember', year=2002, genre='Romance', director='Adam Shankman', cast=['Mandy Moore', 'Shane West', 'Peter Coyote'], avg_rating=7.4, poster_url='https://image.tmdb.org/t/p/w500/8lUYMvWdHA0Q0k5F76RQCeCBUkA.jpg', description='The story of two North Carolina teens who come of age through an unlikely romance.'),
    # Sci-Fi
    dict(tmdb_id=27205,  title='Inception', year=2010, genre='Sci-Fi', director='Christopher Nolan', cast=['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'], avg_rating=8.8, poster_url='https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', description='A thief who steals corporate secrets through dream-sharing technology is given the inverse task.'),
    dict(tmdb_id=157336, title='Interstellar', year=2014, genre='Sci-Fi', director='Christopher Nolan', cast=['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'], avg_rating=8.6, poster_url='https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', description="A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival."),
    dict(tmdb_id=603,    title='The Matrix', year=1999, genre='Sci-Fi', director='Lana Wachowski', cast=['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'], avg_rating=8.7, poster_url='https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', description='A hacker discovers reality is a simulation and joins a rebellion against its machine overlords.'),
    dict(tmdb_id=329865, title='Arrival', year=2016, genre='Sci-Fi', director='Denis Villeneuve', cast=['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'], avg_rating=7.9, poster_url='https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg', description='A linguist is recruited to communicate with aliens after twelve mysterious spacecraft appear.'),
    dict(tmdb_id=335984, title='Blade Runner 2049', year=2017, genre='Sci-Fi', director='Denis Villeneuve', cast=['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'], avg_rating=8.0, poster_url='https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg', description='A new blade runner unearths a long-buried secret that could plunge society into chaos.'),
    dict(tmdb_id=264660, title='Ex Machina', year=2014, genre='Sci-Fi', director='Alex Garland', cast=['Alicia Vikander', 'Domhnall Gleeson', 'Oscar Isaac'], avg_rating=7.7, poster_url='https://image.tmdb.org/t/p/w500/dmJW8IAKHKxFNiUnoDR7JfsK7Rp.jpg', description='A programmer is selected to evaluate an AI housed in a humanoid robot.'),
    # Comedy
    dict(tmdb_id=18785,  title='The Hangover', year=2009, genre='Comedy', director='Todd Phillips', cast=['Bradley Cooper', 'Ed Helms', 'Zach Galifianakis'], avg_rating=7.7, poster_url='https://image.tmdb.org/t/p/w500/uluhlXubGu1VxU63X9VHCLWDAYP.jpg', description='Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night.'),
    dict(tmdb_id=8363,   title='Superbad', year=2007, genre='Comedy', director='Greg Mottola', cast=['Jonah Hill', 'Michael Cera', 'Emma Stone'], avg_rating=7.6, poster_url='https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg', description='Two co-dependent high school seniors are forced to deal with separation anxiety.'),
    dict(tmdb_id=546554, title='Knives Out', year=2019, genre='Comedy', director='Rian Johnson', cast=['Daniel Craig', 'Ana de Armas', 'Chris Evans'], avg_rating=7.9, poster_url='https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg', description='A detective investigates the death of a patriarch of an eccentric, combative family.'),
    dict(tmdb_id=445571, title='Game Night', year=2018, genre='Comedy', director='John Francis Daley', cast=['Jason Bateman', 'Rachel McAdams', 'Kyle Chandler'], avg_rating=7.0, poster_url='https://image.tmdb.org/t/p/w500/85R8LMyn9f2Lev2YPBF8Nughrkv.jpg', description='A group of friends who meet for a regular game night get entangled in a murder mystery.'),
    dict(tmdb_id=12133,  title='Step Brothers', year=2008, genre='Comedy', director='Adam McKay', cast=['Will Ferrell', 'John C. Reilly', 'Mary Steenburgen'], avg_rating=6.9, poster_url='https://image.tmdb.org/t/p/w500/nvggBbEraUTAVR6ffP3AaBUWSHs.jpg', description='Two middle-aged man-children are forced to live together when their single parents marry.'),
    dict(tmdb_id=55721,  title='Bridesmaids', year=2011, genre='Comedy', director='Paul Feig', cast=['Kristen Wiig', 'Maya Rudolph', 'Rose Byrne'], avg_rating=6.8, poster_url='https://image.tmdb.org/t/p/w500/gJtA7hYsBMQ7EM3sPBMUdBfU7a0.jpg', description="Competition between the maid of honor and a bridesmaid over who is the bride's best friend."),
    # Horror
    dict(tmdb_id=419430, title='Get Out', year=2017, genre='Horror', director='Jordan Peele', cast=['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford'], avg_rating=7.7, poster_url='https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg', description="A young Black man visits his white girlfriend's family estate and discovers a disturbing secret."),
    dict(tmdb_id=447332, title='A Quiet Place', year=2018, genre='Horror', director='John Krasinski', cast=['Emily Blunt', 'John Krasinski', 'Millicent Simmonds'], avg_rating=7.5, poster_url='https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg', description='A family struggles to survive in a post-apocalyptic world inhabited by blind monsters with an acute sense of hearing.'),
    dict(tmdb_id=493922, title='Hereditary', year=2018, genre='Horror', director='Ari Aster', cast=['Toni Collette', 'Alex Wolff', 'Milly Shapiro'], avg_rating=7.3, poster_url='https://image.tmdb.org/t/p/w500/hjlZSXM86wJrfCv5VKfR5DI2VeU.jpg', description='A grieving family is haunted by tragic and disturbing occurrences after the death of their grandmother.'),
    dict(tmdb_id=694,    title='The Shining', year=1980, genre='Horror', director='Stanley Kubrick', cast=['Jack Nicholson', 'Shelley Duvall', 'Danny Lloyd'], avg_rating=8.4, poster_url='https://image.tmdb.org/t/p/w500/nRj5511mZdTl4saWEPoj9QroTIu.jpg', description='A family heads to an isolated hotel for the winter where a sinister presence drives the father into madness.'),
    dict(tmdb_id=458156, title='Us', year=2019, genre='Horror', director='Jordan Peele', cast=["Lupita Nyong'o", 'Winston Duke', 'Elisabeth Moss'], avg_rating=6.8, poster_url='https://image.tmdb.org/t/p/w500/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg', description="A family's vacation turns terrifying when they discover sinister doppelgängers of themselves."),
    dict(tmdb_id=530385, title='Midsommar', year=2019, genre='Horror', director='Ari Aster', cast=['Florence Pugh', 'Jack Reynor', 'William Jackson Harper'], avg_rating=7.1, poster_url='https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg', description='A couple travels to Sweden to attend a midsummer festival that devolves into something sinister.'),
]


class Command(BaseCommand):
    help = 'Seed the database with movies'

    def handle(self, *args, **kwargs):
        created = 0
        for m in MOVIES:
            _, was_created = Movie.objects.get_or_create(tmdb_id=m['tmdb_id'], defaults=m)
            if was_created:
                created += 1
        self.stdout.write(self.style.SUCCESS(f'Seeded {created} movies ({len(MOVIES) - created} already existed)'))
